<?php

declare(strict_types=1);

namespace Terrarium\Application\UseCases\Admin;

use Terrarium\Application\Exceptions\ValidationException;

/**
 * Custom site font: the admin uploads a WOFF2/WOFF/TTF/OTF file, it is stored in
 * public/uploads/fonts and public/uploads/fonts/custom.css is regenerated so both the
 * storefront and the admin panel use it. No database needed.
 */
final class FontService
{
    private const FORMATS = ['woff2' => 'woff2', 'woff' => 'woff', 'ttf' => 'truetype', 'otf' => 'opentype'];

    public function __construct(private readonly string $uploadDir) {}

    private function dir(): string { return $this->uploadDir . '/fonts'; }

    /** @return array{name:string,file:string,url:string,format:string,uploaded_at:string}|null */
    public function current(): ?array
    {
        $f = $this->dir() . '/site-font.json';
        if (!is_file($f)) return null;
        $d = json_decode((string) file_get_contents($f), true);
        return is_array($d) && isset($d['file']) && is_file($this->dir() . '/' . $d['file']) ? $d : null;
    }

    public function upload(string $dataUrl, string $name): array
    {
        if (!preg_match('#^data:[a-z0-9.+/-]*;base64,([A-Za-z0-9+/=\s]+)$#i', $dataUrl, $m)) {
            throw new ValidationException('فایل فونت ارسال نشد.', ['field' => 'font']);
        }
        $bin = base64_decode($m[1], true);
        if ($bin === false || strlen($bin) < 100) throw new ValidationException('فایل فونت معتبر نیست.', ['field' => 'font']);
        if (strlen($bin) > 5 * 1024 * 1024) throw new ValidationException('حجم فونت حداکثر ۵ مگابایت است.', ['field' => 'font']);

        // detect real type from magic bytes (never trust the extension)
        $magic = substr($bin, 0, 4);
        $ext = match (true) {
            $magic === 'wOF2' => 'woff2',
            $magic === 'wOFF' => 'woff',
            $magic === "\x00\x01\x00\x00" || $magic === 'true' => 'ttf',
            $magic === 'OTTO' => 'otf',
            default => null,
        };
        if ($ext === null) throw new ValidationException('فقط فونت WOFF2، WOFF، TTF یا OTF قابل قبول است.', ['field' => 'font']);

        $dir = $this->dir();
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new \RuntimeException('پوشه public/uploads قابل نوشتن نیست. به IIS_IUSRS دسترسی Modify بدهید.');
        }
        $old = $this->current();
        $file = 'font-' . bin2hex(random_bytes(6)) . '.' . $ext;
        if (@file_put_contents($dir . '/' . $file, $bin) === false) {
            throw new \RuntimeException('ذخیره فونت ممکن نشد. دسترسی نوشتن public/uploads را بررسی کنید.');
        }
        $name = trim(preg_replace('/[^\p{L}\p{N} _-]/u', '', $name) ?? '') ?: 'فونت سفارشی';
        $meta = ['name' => mb_substr($name, 0, 60), 'file' => $file, 'url' => '/uploads/fonts/' . $file,
                 'format' => self::FORMATS[$ext], 'uploaded_at' => gmdate('c')];
        file_put_contents($dir . '/site-font.json', json_encode($meta, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
        $this->writeCss($meta);
        if ($old && $old['file'] !== $file) @unlink($dir . '/' . $old['file']);
        return $meta;
    }

    public function remove(): void
    {
        $old = $this->current();
        if ($old) @unlink($this->dir() . '/' . $old['file']);
        @unlink($this->dir() . '/site-font.json');
        $this->writeCss(null);
    }

    private function writeCss(?array $m): void
    {
        $css = "/* generated by admin → ظاهر سایت. Do not edit. */\n";
        if ($m) {
            $css .= "@font-face { font-family: \"SiteCustom\"; src: url(\"{$m['url']}\") format(\"{$m['format']}\"); font-weight: 100 900; font-display: swap; }\n"
                . "body, button, input, select, textarea { font-family: \"SiteCustom\", Vazirmatn, Tahoma, sans-serif !important; }\n";
        }
        @file_put_contents($this->dir() . '/custom.css', $css);
    }
}
